### ISSUE TITLE
Duplicates from matrix

### ISSUE THREAD

**Issue by AlexWayfer** [cirruslabs/cirrus-ci-annotations#20]
Hello.

I have such config:

```yaml
# ...

rspec_task:
  container:
    matrix:
      image: ruby:2.4
      image: ruby:2.5
      image: ruby:2.6
      image: ruby:2.7
  <<: *bundle_cache

  test_script: toys rspec --format=json --out=rspec.json

  always:
    rspec_artifacts:
      path: rspec.json
      type: text/json
      format: rspec
```

And annotations are duplicated from every image:

![image](https://user-images.githubusercontent.com/6510020/88103951-681f9300-cbaa-11ea-9554-52eda25f4e99.png)

It seems logically, but maybe we can collapse, or hide them, or don't report duplicates from matrix?

I'm not sure, if you think that's correct — OK.
